import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const workflow = await readFile('.github/workflows/r1-initial-bootstrap-recovery-deploy-recovery.yml', 'utf8');
const autocontinue = await readFile('.github/workflows/r1-initial-bootstrap-recovery-autocontinue.yml', 'utf8');
const classifier = await readFile('scripts/classify-yandex-initial-bootstrap-recovery-deploy.mjs', 'utf8');
const ciClassifier = await readFile('scripts/classify-github-ci-run.mjs', 'utf8');

test('failed recovery Function deploy has an exact-main read-only metadata recovery path', () => {
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /failed_run_id:/);
  assert.match(workflow, /ci_run_id:/);
  assert.match(workflow, /group: r1-initial-bootstrap-writer[\s\S]*cancel-in-progress: false/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/main'/);
  assert.match(workflow, /\.commit\.sha == \$sha and \.protected == true/);
  assert.match(workflow, /actions\/runs\/\$\{CI_RUN_ID\}/);
  assert.match(workflow, /classify-github-ci-run\.mjs/);
  assert.match(workflow, /RECOVERY_DEPLOY_EXACT_CI_RUN_NOT_PROVEN/);
  assert.match(ciClassifier, /run\.id !== Number\(expectedRunId\)/);
  assert.match(ciClassifier, /run\.head_sha !== expectedSha/);
  assert.match(ciClassifier, /run\.status !== 'completed'/);
  assert.match(ciClassifier, /run\.conclusion !== 'success'/);
  assert.doesNotMatch(workflow, /workflows\/ci\.yml\/runs\?branch=main&event=push&status=success/);
  assert.match(workflow, /RECOVERY_DEPLOY_FAILED_RUN_NOT_LATEST/);
  assert.match(workflow, /Deploy recovery-only Function version/);
  assert.match(workflow, /Invoke exact read-only recovery tag once/);
  assert.match(workflow, /RECOVERY_DEPLOY_FAILURE_PHASE_NOT_PROVEN/);
  assert.match(workflow, /RECOVERY_DEPLOY_WRITER_CONFLICT/);
  assert.match(workflow, /Re-assert exact current main after read-only provider classification/);
});

test('recovery deploy classification reads provider metadata only and publishes an enum artifact', () => {
  assert.match(workflow, /yc serverless function version list/);
  assert.match(workflow, /yc serverless function version list --function-id "\$function_id" --limit 1000/);
  assert.match(workflow, /yc serverless function list-operations --id "\$function_id" --limit 1000/);
  assert.match(workflow, /yc serverless function version get-by-tag/);
  assert.match(workflow, /serverless-functions\.api\.cloud\.yandex\.net\/functions\/v1\/functions\/\$\{function_id\}:tagHistory/);
  assert.match(workflow, /data-urlencode "tag=\$\{TARGET_TAG\}"/);
  assert.match(workflow, /data-urlencode 'pageSize=1000'/);
  assert.match(workflow, /resource-manager\.api\.cloud\.yandex\.net\/resource-manager\/v1\/folders/);
  assert.match(workflow, /YC_CLOUD_ID: \$\{\{ secrets\.YC_R1_CLOUD_ID \}\}/);
  assert.match(workflow, /if \[ -z "\$YC_CLOUD_ID" \]/);
  assert.match(workflow, /data-urlencode "cloudId=\$\{cloud_id\}"/);
  assert.match(workflow, /audittrails\.api\.cloud\.yandex\.net\/audit-trails\/v1\/trails/);
  assert.match(workflow, /data-urlencode "folderId=\$\{cloud_folder_ids\[\$index\]\}"/);
  assert.match(workflow, /yc logging read --group-id "\$audit_log_group_id"/);
  assert.match(workflow, /json_payload\.eventType = \\"yandex\.cloud\.audit\.serverless\.functions\.CreateFunctionVersion/);
  assert.match(workflow, /--audit-cloud-trails "\$tmp\/cloud-folders\.json" "\$cloud_id" "\$YC_FOLDER_ID"/);
  assert.match(workflow, /--audit-cloud-folder-ids "\$tmp\/cloud-folders\.json" "\$cloud_id" "\$YC_FOLDER_ID"/);
  assert.match(workflow, /data-urlencode 'pageSize=1000'/);
  assert.match(classifier, /folders\.length > 100/);
  assert.match(workflow, /--audit-events "\$tmp\/audit-events\.json"/);
  assert.match(workflow, /auditTrailSourceEvidence:\$audit_trail,auditSourceDecision:\$audit_source_decision,auditCreateFunctionVersionEvidence:\$audit_event/);
  assert.match(workflow, /EXISTING_APPLICABLE_AUDIT_SOURCE\|NO_APPLICABLE_PREEXISTING_AUDIT_SOURCE\|SOURCE_EVIDENCE_UNUSABLE\|SOURCE_EVIDENCE_AMBIGUOUS/);
  assert.match(workflow, /runtime_sa="\$\(yc iam service-account get/);
  assert.match(workflow, /"\$YC_WIF_SERVICE_ACCOUNT_ID" "\$runtime_sa"/);
  assert.match(workflow, /classify-yandex-initial-bootstrap-recovery-deploy\.mjs/);
  assert.match(workflow, /CREATE_OPERATION_AMBIGUOUS\|CREATE_OPERATION_IN_PROGRESS/);
  assert.match(workflow, /RECOVERY_TAGGED_VERSION_CANDIDATE_PRESENT\|RECOVERY_TAGGED_VERSION_NOT_OBSERVED_IN_WINDOW/);
  assert.match(workflow, /RECOVERY_DEPLOY_INPUT_INVALID\|RECOVERY_VERSION_ENTRY_INVALID\|RECOVERY_VERSION_TAGS_INVALID\|RECOVERY_VERSION_TIMESTAMP_INVALID\|RECOVERY_METADATA_JSON_INVALID\|RECOVERY_CLASSIFIER_INTERNAL_ERROR\|RECOVERY_TAG_HISTORY_READ_FAILED\|RECOVERY_TAG_HISTORY_METADATA_INVALID\|RECOVERY_TAG_HISTORY_INCOMPLETE\|RECOVERY_TAG_HISTORY_AMBIGUOUS\|RECOVERY_TAG_HISTORY_VERSION_NOT_OBSERVED\|RECOVERY_TAG_HISTORY_VERSION_CANDIDATE_PRESENT\|RECOVERY_UNTAGGED_VERSION_CANDIDATE_PRESENT\|RECOVERY_UNTAGGED_VERSION_AMBIGUOUS\|RECOVERY_UNTAGGED_VERSION_METADATA_UNPROVEN\|RECOVERY_VERSION_LIST_INCOMPLETE\|RECOVERY_OPERATION_LIST_INCOMPLETE\) ;;/);
  assert.match(workflow, /AUDIT_TRAIL_METADATA_INVALID\|AUDIT_TRAIL_LIST_INCOMPLETE\|AUDIT_TRAIL_SOURCE_NOT_CONFIGURED/);
  assert.match(workflow, /--audit-trail-http-status "\$trail_list_http"/);
  assert.match(workflow, /--audit-folder-list-http-status "\$folder_list_http"/);
  assert.match(workflow, /AUDIT_TRAIL_AUTHENTICATION_REQUIRED/);
  assert.match(workflow, /AUDIT_TRAIL_FOLDER_LIST_PERMISSION_DENIED/);
  assert.match(workflow, /AUDIT_TRAIL_FOLDER_STATUS_UNSUPPORTED/);
  assert.match(workflow, /AUDIT_TRAIL_TARGET_FOLDER_NOT_ACTIVE/);
  assert.match(workflow, /AUDIT_TRAIL_FOLDER_CLOUD_ID_MISMATCH/);
  assert.match(workflow, /AUDIT_TRAIL_FOLDER_LIST_AMBIGUOUS/);
  assert.match(workflow, /AUDIT_TRAIL_FOLDER_STATUS_MISSING/);
  assert.match(workflow, /AUDIT_TRAIL_CLOUD_COVERAGE_INPUT_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_LIST_RESPONSE_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_LIST_ROOT_INVALID/);
  assert.match(classifier, /function protobufRepeatedField\(record, name\)/);
  assert.match(classifier, /protobufRepeatedField\(response, 'trails'\)/);
  assert.match(classifier, /Protobuf JSON omits empty repeated fields/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_PAGE_TOKEN_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_LIST_COUNT_MISMATCH/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_JSON_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_FOLDER_MISMATCH/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_CLOUD_ID_MISMATCH/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_TIMESTAMPS_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_DESTINATION_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TRAIL_JSON_INVALID/);
  assert.match(workflow, /AUDIT_TRAIL_TARGET_FOLDER_NOT_FOUND/);
  assert.match(workflow, /AUDIT_TRAIL_COVERAGE_UNPROVEN/);
  assert.doesNotMatch(workflow, /resource-manager\.api\.cloud\.yandex\.net\/resource-manager\/v1\/folders\/\$\{YC_FOLDER_ID\}/);
  assert.match(workflow, /AUDIT_LOG_READ_FAILED\|AUDIT_LOG_READ_PERMISSION_DENIED\|AUDIT_LOG_LIST_INCOMPLETE/);
  assert.match(workflow, /r1-initial-bootstrap-recovery-deploy-evidence-/);
  assert.match(workflow, /actions\/upload-artifact@/);
  assert.doesNotMatch(workflow, /yc serverless function version create/);
  assert.doesNotMatch(workflow, /yc serverless function invoke/);
  assert.doesNotMatch(workflow, /add-access-binding|set-access-bindings|yc logging group create|yc audit-trails trail create/);
  assert.doesNotMatch(workflow, /Google|YDB|Lockbox|source_records|migration_runs/);
  assert.match(classifier, /ENUMS\.has\(result\) \? result : 'DIAGNOSTIC_FAILED'/);
  assert.doesNotMatch(classifier, /process\.stderr|console\.(?:log|error)/);
});

test('recovery autocontinue routes only its allowlisted exact-run recovery markers', () => {
  assert.match(autocontinue, /READ_ONLY_FUNCTION_DEPLOY_CLASSIFICATION/);
  assert.match(autocontinue, /DEPLOYMENT_OUTCOME_UNCLASSIFIED/);
  assert.match(autocontinue, /Recovery-Run-ID: \[1-9\]\[0-9\]\*/);
  assert.match(autocontinue, /DEPLOY_RUN_NOT_LATEST_FAILED/);
  assert.match(autocontinue, /DEPLOY_RUN_PHASE_NOT_PROVEN/);
  assert.match(autocontinue, /Deploy recovery-only Function version" and \.conclusion == "failure"/);
  assert.match(autocontinue, /Invoke exact read-only recovery tag once" and \.conclusion == "skipped"/);
  assert.match(autocontinue, /r1-initial-bootstrap-recovery-deploy-recovery\.yml/);
  assert.match(autocontinue, /ci_run_id:\$ci_run_id/);
  assert.match(autocontinue, /SOURCE_CI_RUN_ID/);
  assert.match(autocontinue, /inputs:\{failed_run_id:\$run_id,ci_run_id:\$ci_run_id\}/);
  assert.match(autocontinue, /"\$api\/actions\/workflows\/\$recovery_workflow\/dispatches"/);
  assert.match(autocontinue, /RECOVERY_AUTOCONTINUE_DEPLOY_CLASSIFICATION_CHANGESET_INVALID/);
  assert.match(autocontinue, /any\(\.\[]; \.filename == \$test and \.status != "removed"\)/);
  assert.match(autocontinue, /\.filename == "\.github\/workflows\/r1-initial-bootstrap-recovery-autocontinue\.yml"/);
  assert.match(autocontinue, /\.filename == "\.github\/workflows\/r1-initial-bootstrap-recovery-deploy-recovery\.yml"/);
  assert.match(autocontinue, /\.filename == "scripts\/classify-yandex-initial-bootstrap-recovery-deploy\.mjs"/);
  assert.match(autocontinue, /or\s+\([\s\S]*any\(\.\[]; \.filename == "\.github\/workflows\/r1-initial-bootstrap-recovery-deploy-recovery\.yml"/);
  assert.match(autocontinue, /\.github\/workflows\/r1-initial-bootstrap-recovery-deploy-recovery\.yml/);
  assert.match(autocontinue, /scripts\/classify-yandex-initial-bootstrap-recovery-deploy\.mjs/);
  assert.match(autocontinue, /RECOVERY_AUTOCONTINUE_DEPLOY_RUN_NOT_LATEST_FAILED/);
  assert.match(autocontinue, /RECOVERY_AUTOCONTINUE_DEPLOY_RUN_PHASE_NOT_PROVEN/);
  assert.match(autocontinue, /actions\/workflows\/r1-initial-bootstrap-recovery\.yml\/runs\?branch=main&event=workflow_dispatch&status=failure/);
  assert.match(autocontinue, /Deploy recovery-only Function version" and \.conclusion == "failure"/);
  assert.match(autocontinue, /Invoke exact read-only recovery tag once" and \.conclusion == "skipped"/);
  assert.match(autocontinue, /OWNER_AUTHORIZED_SINGLE_RECOVERY_DEPLOY/);
  assert.match(autocontinue, /RECOVERY_ONLY_FUNCTION_VERSION_CREATE_CLASSIFIED/);
  assert.match(autocontinue, /capture\("\^R1 #\(\?<number>\[1-9\]\[0-9\]\*\):"\)\.number/);
  assert.doesNotMatch(autocontinue, /tracking_issue_number='(?:453|630)'/);
  assert.match(autocontinue, /\$api\/issues\/\$\{tracking_issue_number\}/);
  assert.match(autocontinue, /r1-initial-bootstrap-recovery-deploy-attempt\.yml/);
  assert.match(autocontinue, /RECOVERY_DEPLOY_ATTEMPT_CHANGESET_INVALID/);
  assert.match(autocontinue, /workflow_runs \| length/);
  assert.match(autocontinue, /R1_RECOVERY_DEPLOY_ATTEMPT_SAME_SHA_REPLAY_FORBIDDEN/);
  assert.match(autocontinue, /prior_attempt_status" != 'completed'/);
  assert.match(autocontinue, /R1_RECOVERY_DEPLOY_ATTEMPT_ALREADY_CONSUMED_OR_UNCLASSIFIED/);
  assert.match(autocontinue, /\.name == "Create exactly one read-only recovery Function version without invoking it"/);
  assert.match(autocontinue, /Create exactly one read-only recovery Function version without invoking it"\s+and \.conclusion == "skipped"/);
  assert.match(autocontinue, /\.github\/workflows\/r1-initial-bootstrap-recovery-autocontinue\.yml/);
  assert.match(autocontinue, /tests\/tooling\/r1-initial-bootstrap-recovery-autocontinue-workflow\.test\.mjs/);
  assert.match(autocontinue, /\.filename == "AGENTS\.md"/);
  assert.match(autocontinue, /\.filename == "docs\/R1_COMPLETION_SPRINT\.md"/);
});

test('deploy-only retry is exact-run bounded, emits safe failure enums and never invokes the Function', async () => {
  const attemptWorkflow = (await readFile(
    '.github/workflows/r1-initial-bootstrap-recovery-deploy-attempt.yml', 'utf8',
  )).replace(/\r\n/g, '\n');
  const attemptClassifier = (await readFile(
    'scripts/classify-yandex-initial-bootstrap-recovery-deploy-attempt.mjs', 'utf8',
  )).replace(/\r\n/g, '\n');
  assert.match(attemptWorkflow, /workflow_dispatch:[\s\S]*failed_run_id:[\s\S]*ci_run_id:[\s\S]*source_pr_number:/);
  assert.match(attemptWorkflow, /group: r1-initial-bootstrap-writer[\s\S]*cancel-in-progress: false/);
  assert.match(attemptWorkflow, /INITIAL_BOOTSTRAP_RECOVERY_DEPLOY_FAILED/);
  assert.match(attemptWorkflow, /Invoke exact read-only recovery tag once/);
  assert.match(attemptWorkflow, /and \.conclusion == "skipped"/);
  assert.match(attemptWorkflow, /latest_failed_id/);
  assert.match(attemptWorkflow, /GITHUB_RUN_ATTEMPT/);
  assert.match(attemptWorkflow, /RECOVERY_DEPLOY_ATTEMPT_ALREADY_USED_FOR_SHA/);
  assert.match(attemptWorkflow, /Create exactly one read-only recovery Function version without invoking it/);
  assert.match(attemptWorkflow, /classify-yandex-initial-bootstrap-recovery-deploy-attempt\.mjs/);
  assert.match(attemptWorkflow, /actions\/upload-artifact@/);
  assert.doesNotMatch(attemptWorkflow, /yc serverless function invoke/);
  assert.doesNotMatch(attemptWorkflow, /migration_runs|source_records|source_snapshots/);
  assert.doesNotMatch(attemptWorkflow, /secret get-payload/);
  assert.match(attemptClassifier, /PERMISSION_DENIED/);
  assert.match(attemptClassifier, /permissionBoundary/);
  assert.match(attemptClassifier, /RECOVERY_FUNCTION_VERSION_CREATE_ACCEPTED_NO_INVOKE/);
  assert.doesNotMatch(attemptClassifier, /process\.stderr|console\.(?:log|error)/);
});
